### ISSUE TITLE
fab_gate closeout validator silently unregistered on every fresh install of main (import-order cycle via closeout → closeout_validators → fab_gate → panel_invoker → events → closeout)

### ISSUE THREAD

**Issue by ViperJuice** [Consiliency/agent-harness#819]
## Observed

On a fresh install of \`origin/main\` (\`c98573eb\`) — \`uv pip install phase-loop-runtime/\` into an empty venv, or \`PYTHONPATH=src\` — the very first import of \`phase_loop_runtime.cli\` prints:

\`\`\`
built-in closeout validator fab_gate is not importable; gate NOT registered
(ImportError: cannot import name 'phase_loop_closeout_diagnostic' from partially
initialized module 'phase_loop_runtime.closeout' (most likely due to a circular import))
\`\`\`

so only 4 of the 5 built-in closeout gates are registered in that interpreter. The PyPI \`0.7.14\` wheel does **not** exhibit it.

## Bisect

\`git bisect run\` between \`v0.7.14\` (good) and \`origin/main\` (bad), test = "does \`python -m phase_loop_runtime.cli --version\` print \`gate NOT registered\`", names **\`b09b1a47\` — Consiliency/agent-harness#787** (\`fix(gates): make closeout gate failures visible (G-1, G-2, G-6)\`) as the first bad commit.

That commit's own message already records the mechanism and defers it: *"when \`runner\` is imported before \`closeout_validators\`, only 4 of the 5 built-ins register — \`fab_gate\` … The import-order fragility needs its own issue."* This is that issue. ah#787 made the pre-existing G-2 fail-open **visible** (good) but the underlying cycle is still there, and on main the default CLI import order hits it every time — so it is not "fragile", it is the steady state.

## Cycle (from \`python -X importtime\`)

\`cli\` → \`closeout\` → \`closeout_validators\` (registers built-ins by importing them) → \`fab_gate\` → \`panel_invoker\` → \`events\` → \`from .closeout import phase_loop_closeout_diagnostic\` while \`closeout\` is still partially initialised → ImportError → \`fab_gate\` dropped from the registry.

\`events.py:8\` and \`runner.py:72\` are the two consumers of \`phase_loop_closeout_diagnostic\`.

## Why it matters

- Every governed closeout run from a git-pinned runtime (the fleet re-pin path for Consiliency/agent-harness#789 Lane D5 is \`uv tool install --force git+…@<main sha>\`) runs **without** the FAB gate. The warning goes to stderr once at import and is easy to miss under \`nohup\`.
- The WARNING is the only signal; there is no test asserting that all five built-ins register under the CLI's real import order.

## Suggested fix

Break the cycle at \`events.py\` (lazy/late import of \`phase_loop_closeout_diagnostic\`, or move the diagnostic helper into a leaf module), then add a test that imports \`phase_loop_runtime.cli\` in a fresh subprocess and asserts the registry holds all 5 built-ins with no \`gate NOT registered\` output.

Found while preparing Consiliency/agent-harness#789 Lane D5 (runtime re-pin probe); out of scope for that lane.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Rv2aKsUWdEKoWfB5PTpD1B

**Comment by ViperJuice** [comment]
Still open and now reproducing on a second install path, so recording the wider blast radius.

While preparing Lane D5 of Consiliency/agent-harness#789 the runtime on `claw` was re-pinned from `463b90c3` to `c98573eb` (`origin/main`) with `uv tool install --force`. The warning fires on that install too:

```
built-in closeout validator fab_gate is not importable; gate NOT registered
(ImportError: cannot import name 'phase_loop_closeout_diagnostic' from partially
initialized module 'phase_loop_runtime.closeout' (most likely due to a circular import))
```

Two observations worth having on the record:

1. **The reported symbol varies with the import path.** Running through the CLI it reports `cannot import name 'phase_loop_closeout_diagnostic' from … closeout`; running the board launcher under `PYTHONPATH=src` it reports `cannot import name 'SeatOutcomeRecord' from partially initialized module 'phase_loop_runtime.panel_invoker'`. Same cycle, different first casualty depending on which module the process imports first — so a fix must break the cycle, not special-case one symbol.

2. **It is noise ahead of real output in operator tooling.** Every FABPUB rotation helper (`fabpub_v3_probe.py`, `fabpub_rotation_preflight.py`) prints this before its own first line, so the runbook has to tell operators to expect it and not read it as a failure of the ceremony (`docs/fabpub-partition-rotation-runbook.md` §2.1, §9). Consiliency/agent-harness#822 adds a second unrelated warning on the same first-import path under Python 3.13. An operator running a state-changing ceremony now reads two warnings before any real output — the cost is that a *real* warning is easy to miss in that company.

The rotation verb itself is unaffected; this remains cosmetic for FABPUB and real for closeout, where the gate is silently not registered.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01Rv2aKsUWdEKoWfB5PTpD1B

**Comment by ViperJuice** [comment]
Consumer-side verification from omniagent-plus on 2026-09-10, using the installed CLI interpreter git-pinned at c98573ebd45452451ce719406f5b28379284b4c9 (reports 0.7.14): the startup defect still reproduces, but its closeout impact is narrower than the issue description implies.

In a fresh process, importing phase_loop_runtime.cli yields 4 registered validators and unavailable={fab_gate}. Calling the normal run_closeout_validators path with PHASE_LOOP_REVIEW=block (passed through its env argument), using a synthetic CloseoutContext with a run_id but no repo_root, then yields 5 registered validators, an empty unavailable set, and fab_delta_review_gate_block at block severity. Exit 0 after asserting both recovery and the blocking negative control. No manual preload, registry mutation, monkeypatch, runtime upgrade, or publication-state mutation was used.

The installed closeout_validators.py retries unavailable built-ins before snapshotting the registry. This disproves a permanent missing-gate inference based on startup alone for this import path. It does NOT fix startup, prove all import orders, certify a real candidate, or establish end-to-end governed publication. Keep the issue open for the startup-cycle repair and fresh-process regression coverage. We are attempting one normal TRIAGE runner action with blocking review checks and manual closeout; no commit/push/publish is authorized by this synthetic probe.

**Comment by ViperJuice** [comment]
Consumer confirmation from Consiliency/Code-Index-MCP on 2026-09-11. Adding to Consiliency/agent-harness#819 rather than filing a duplicate.

### Installed runtime and reproduction

- phase-loop CLI entrypoint uses the uv tool interpreter, Python 3.13.12.
- Distribution reports 0.7.14, installed non-editably from git commit `c98573ebd45452451ce719406f5b28379284b4c9` (direct-url VCS metadata).
- `phase-loop validate-roadmap specs/phase-plans-v13.md` reproduces the circular-import warning, then exits 0 with eight valid phases.
- The standalone panel path also reproduces it. This consumer has held off automated implementation pending gate verification; the warning does not invalidate the separate completed planning-panel responses.

### Fresh-process negative controls

I independently confirmed and extended the latest comment to BOTH import orders using the installed interpreter, working directory /tmp:

| First import | Startup failure symbol | Before normal closeout | After normal closeout | Invalid FAB input |
| --- | --- | --- | --- | --- |
| phase_loop_runtime.cli | phase_loop_closeout_diagnostic | 4 registered; fab_gate unavailable | 5 registered; none unavailable | fab_delta_review_gate_block, severity block |
| phase_loop_runtime.panel_invoker | SeatOutcomeRecord | 4 registered; fab_gate unavailable | 5 registered; none unavailable | fab_delta_review_gate_block, severity block |

Each probe imports the entry module first, then calls the public `run_closeout_validators` with `env={"PHASE_LOOP_REVIEW": "block"}` and a synthetic `CloseoutContext` containing `fab_gate_inputs={"run_id": "code-index-819-probe"}` but no repo_root. Both exit 0 after asserting recovery and the blocking negative control.

No preload of fab_gate, registry mutation, monkeypatch, runtime upgrade, provider call, source fix, publication, or phase-state mutation was used. No real candidate acceptance is claimed.

### Impact and requested regression coverage

This confirms a real startup/import-cycle bug owned by agent-harness, but NOT permanent loss of FAB enforcement on these two normal-closeout paths. The built-in retry mitigates the startup omission. The issue title/body should be read alongside that narrower verified impact.

Please retain fresh-subprocess regressions for both real CLI and standalone panel entry imports: all five built-ins registered without the warning, plus the blocking negative control with PHASE_LOOP_REVIEW=block. Preserve the existing fail-closed behavior when a gate genuinely cannot be loaded. A fix must remove the import cycle, not hide the warning or weaken the gate.

Consiliency/Code-Index-MCP v13 planning review remains a separate artifact-level result; this synthetic check does not certify end-to-end governed execution or publication.

**Comment by ViperJuice** [comment]
Fresh verification on merged main7860127e7e8e63ad84d9f628855ffbf73f4f42cd (phase-loop-runtime0.7.14), built into a clean isolated installation: the native phase-loop CLI entrypoint with `--help` exits0 but still emits `built-in closeout validator fab_gate is not importable; gate NOT registered`, identifying the same partially initialized closeout-module circular import.

This confirms agent-harness#819 remains live after agent-harness#834. The two merged publication/store test files pass133/133 with per-test installed-module hash guards; that bounded green result is not healthy closeout registration or full-runtime acceptance. Logs, exact installed wheel/source hashes and JUnit are retained. No publication, status command, authority mutation or retry of an ambiguous operation was performed. Existing draft agent-harness#827 and its publication-ownership hold remain unchanged.
